version: '3'
services:
  server:
    image: demo
    restart: unless-stopped
    depends_on:
    - kafka
    build:
      context: ./
      dockerfile: Dockerfile

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    logging:
      driver: none
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    logging:
      driver: none
    restart: unless-stopped
    depends_on:
    - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
